version: "2"
services:
  fluent:
    build: 
      context: .
      dockerfile: Dockerfile.loki
    image: diogok/fluentbit:loki-0.0.5
    environment:
      HTTP_HOST: bit2loki
      HTTP_PORT: 5000
    ports:
      - 9514:9514/udp
      - 9515:9515/udp
      - 24224:24224/udp
      - 5432:5432/udp
      - 9600:9600

  bit2loki:
    image: diogok/fluentbit-http-to-loki:0.0.1
    environment:
      LOKI_HOST: loki
      LOKI_PORT: 3100

  loki:
    image: grafana/loki:latest
    ports:
      - 3100:3100
    command: -config.file=/etc/loki/local-config.yaml

  grafana:
    image: grafana/grafana:master
    ports:
      - "3000:3000"
